/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author seb
 */
public class View extends javax.swing.JApplet implements ViewBehaviour {

    /**
     * 
     * Initializes the applet View
     */
    
    private Controller controller;
    
    
    private StyledDocument hackerView, infoView;
    private Style  errorStyle, infoStyle, attackStyle, cmdStyle;
    
    
    @Override
    public void init() {
        Controller ctrl = new Controller(this);
        this.setController(ctrl);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents(); 
                    entryPanel.setVisible(true); 
                    missionLayeredPanel.setVisible(false);
                    
                    /*
                    * styles' initialization
                    * Red for error printed for user
                    */
                    infoView = infoPane.getStyledDocument();
                    errorStyle = infoPane.addStyle("errStyle", null);
                    infoStyle = infoPane.addStyle("infoStyle", null);
                    
                    hackerView = hackerPane.getStyledDocument();
                    attackStyle = hackerPane.addStyle("attackStyle",null);
                    cmdStyle = hackerPane.addStyle("cmdStyle",null);
                    
                    StyleConstants.setForeground(infoStyle, Color.BLACK);
                    StyleConstants.setForeground(errorStyle, Color.RED);
                    StyleConstants.setForeground(attackStyle,Color.BLACK);
                    StyleConstants.setForeground(cmdStyle,Color.GRAY);
                    
                   
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutPanel = new javax.swing.JLayeredPane();
        entryPanel = new javax.swing.JPanel();
        entryPanelTitle = new javax.swing.JLabel();
        entryPanelButton = new javax.swing.JButton();
        entryPanelScrollPanel = new javax.swing.JScrollPane();
        entryPanelText = new javax.swing.JTextArea();
        controlPanel = new javax.swing.JPanel();
        viewPanel = new javax.swing.JPanel();
        hackerLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        scrollInfoPane = new javax.swing.JScrollPane();
        infoPane = new javax.swing.JTextPane();
        scrollHackPane = new javax.swing.JScrollPane();
        hackerPane = new javax.swing.JTextPane();
        missionLayeredPanel = new javax.swing.JLayeredPane();
        mission1Panel = new javax.swing.JPanel();
        m1HashField = new javax.swing.JTextField();
        m1Filebutton = new javax.swing.JButton();
        m1HashButton = new javax.swing.JButton();
        mission2Panel = new javax.swing.JPanel();
        m2ChoisirDic = new javax.swing.JLabel();
        m2ListDic = new javax.swing.JComboBox();
        m2TextField = new javax.swing.JTextField();
        m2AutoButton = new javax.swing.JButton();
        m2AddWordButton = new javax.swing.JButton();
        mission3Panel = new javax.swing.JPanel();
        m3FillDicoButton = new javax.swing.JButton();
        m3AttakButton = new javax.swing.JButton();
        m3ConfirmButton = new javax.swing.JButton();
        m3PassField = new javax.swing.JTextField();

        layoutPanel.setPreferredSize(new java.awt.Dimension(720, 430));

        entryPanel.setPreferredSize(new java.awt.Dimension(720, 430));

        entryPanelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entryPanelTitle.setText("Bienvenue sur l'applet de Brute Force");

        entryPanelButton.setText("Commencer");
        entryPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryPanelButtonActionPerformed(evt);
            }
        });

        entryPanelScrollPanel.setBackground(new java.awt.Color(238, 238, 238));
        entryPanelScrollPanel.setBorder(null);

        entryPanelText.setEditable(false);
        entryPanelText.setBackground(new java.awt.Color(238, 238, 238));
        entryPanelText.setColumns(20);
        entryPanelText.setRows(5);
        entryPanelText.setText("Dans cette applet vous allez découvrir comment se passe une vrai attaque par brute force. \nVous allez devoir trouver un mot de passe que nous avons perdu. Dès que vous êtes près \nappuyez sur commencer");
        entryPanelText.setBorder(null);
        entryPanelScrollPanel.setViewportView(entryPanelText);

        javax.swing.GroupLayout entryPanelLayout = new javax.swing.GroupLayout(entryPanel);
        entryPanel.setLayout(entryPanelLayout);
        entryPanelLayout.setHorizontalGroup(
            entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryPanelLayout.createSequentialGroup()
                .addGroup(entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entryPanelLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(entryPanelButton))
                    .addGroup(entryPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(entryPanelScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(entryPanelLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(entryPanelTitle)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        entryPanelLayout.setVerticalGroup(
            entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(entryPanelTitle)
                .addGap(54, 54, 54)
                .addComponent(entryPanelScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(entryPanelButton)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        controlPanel.setPreferredSize(new java.awt.Dimension(720, 430));

        viewPanel.setPreferredSize(new java.awt.Dimension(720, 430));

        hackerLabel.setText("hacker view");

        infoLabel.setText("info view");

        scrollInfoPane.setViewportView(infoPane);

        scrollHackPane.setViewportView(hackerPane);

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(hackerLabel)
                .addGap(300, 300, 300)
                .addComponent(infoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollHackPane, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(scrollInfoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hackerLabel)
                    .addComponent(infoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollInfoPane)
                    .addComponent(scrollHackPane, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addContainerGap())
        );

        missionLayeredPanel.setPreferredSize(new java.awt.Dimension(720, 149));

        mission1Panel.setPreferredSize(new java.awt.Dimension(720, 149));

        m1HashField.setForeground(new java.awt.Color(204, 204, 204));
        m1HashField.setText("copy the hash");

        m1Filebutton.setText("fichier mot de passe");
        m1Filebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1FilebuttonActionPerformed(evt);
            }
        });

        m1HashButton.setText("confirm hash");

        javax.swing.GroupLayout mission1PanelLayout = new javax.swing.GroupLayout(mission1Panel);
        mission1Panel.setLayout(mission1PanelLayout);
        mission1PanelLayout.setHorizontalGroup(
            mission1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mission1PanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(m1Filebutton)
                .addGap(0, 477, Short.MAX_VALUE))
            .addGroup(mission1PanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(m1HashField, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(m1HashButton)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        mission1PanelLayout.setVerticalGroup(
            mission1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mission1PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(m1Filebutton)
                .addGap(50, 50, 50)
                .addGroup(mission1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m1HashField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m1HashButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        m2ChoisirDic.setText("Choisir dictionnaire");

        m2ListDic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "wordlist", "disneyland", "motsfrancais" }));

        m2TextField.setForeground(new java.awt.Color(204, 204, 204));
        m2TextField.setText("Entrer un mot");

        m2AutoButton.setText("auto remplissage");

        m2AddWordButton.setText("ajouter mot au dictionnaire");

        javax.swing.GroupLayout mission2PanelLayout = new javax.swing.GroupLayout(mission2Panel);
        mission2Panel.setLayout(mission2PanelLayout);
        mission2PanelLayout.setHorizontalGroup(
            mission2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mission2PanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(mission2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mission2PanelLayout.createSequentialGroup()
                        .addComponent(m2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(m2AddWordButton)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(mission2PanelLayout.createSequentialGroup()
                        .addGroup(mission2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(m2ListDic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m2ChoisirDic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(m2AutoButton)
                        .addGap(56, 56, 56))))
        );
        mission2PanelLayout.setVerticalGroup(
            mission2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mission2PanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(m2ChoisirDic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mission2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m2ListDic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m2AutoButton))
                .addGap(19, 19, 19)
                .addGroup(mission2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m2AddWordButton)
                    .addComponent(m2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        m3FillDicoButton.setText("remplir dictionnaire");

        m3AttakButton.setText("lancer attaque");

        m3ConfirmButton.setText("confirm pwd");

        m3PassField.setForeground(new java.awt.Color(204, 204, 204));
        m3PassField.setText("Entrer le mot de passe");

        javax.swing.GroupLayout mission3PanelLayout = new javax.swing.GroupLayout(mission3Panel);
        mission3Panel.setLayout(mission3PanelLayout);
        mission3PanelLayout.setHorizontalGroup(
            mission3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mission3PanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(mission3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mission3PanelLayout.createSequentialGroup()
                        .addComponent(m3PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(m3ConfirmButton))
                    .addGroup(mission3PanelLayout.createSequentialGroup()
                        .addComponent(m3FillDicoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(m3AttakButton)))
                .addGap(62, 62, 62))
        );
        mission3PanelLayout.setVerticalGroup(
            mission3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mission3PanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(mission3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m3FillDicoButton)
                    .addComponent(m3AttakButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(mission3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m3ConfirmButton)
                    .addComponent(m3PassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout missionLayeredPanelLayout = new javax.swing.GroupLayout(missionLayeredPanel);
        missionLayeredPanel.setLayout(missionLayeredPanelLayout);
        missionLayeredPanelLayout.setHorizontalGroup(
            missionLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(missionLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(missionLayeredPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mission1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(missionLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(missionLayeredPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mission2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(missionLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(missionLayeredPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mission3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        missionLayeredPanelLayout.setVerticalGroup(
            missionLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
            .addGroup(missionLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(missionLayeredPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mission1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(missionLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(missionLayeredPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mission2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(missionLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(missionLayeredPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mission3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        missionLayeredPanel.setLayer(mission1Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        missionLayeredPanel.setLayer(mission2Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        missionLayeredPanel.setLayer(mission3Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(missionLayeredPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addComponent(viewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(missionLayeredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layoutPanelLayout = new javax.swing.GroupLayout(layoutPanel);
        layoutPanel.setLayout(layoutPanelLayout);
        layoutPanelLayout.setHorizontalGroup(
            layoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layoutPanelLayout.setVerticalGroup(
            layoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layoutPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layoutPanel.setLayer(entryPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layoutPanel.setLayer(controlPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entryPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryPanelButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("## view : commencer > pressed ##");
        entryPanel.setVisible(false);
        controller.initMission1();
        missionLayeredPanel.setVisible(true);
        mission2Panel.setVisible(false);
        mission3Panel.setVisible(false);
        mission1Panel.setVisible(true);
    }//GEN-LAST:event_entryPanelButtonActionPerformed

    private void m1FilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1FilebuttonActionPerformed
        // TODO add your handling code here:
        FileReader fr;
        BufferedReader br ;
        String newLine;
        
        System.out.println("## view : m1FileButton > pressed ##");
        try{
            fr = new FileReader(controller.getModel().getPasswordFile());
            br = new BufferedReader(fr);
            System.out.println("## view : m1FileButton ... file initialized ##");
            while((newLine = br.readLine()) != null){
                System.out.println("## view : m1FileButton ... reading line ##");
                hackerView.insertString(hackerView.getLength(),"hacker01~$ cat .password\n",cmdStyle);
                hackerView.insertString(hackerView.getLength(),newLine+"\n",attackStyle);
                infoView.insertString(infoView.getLength(),"<<= see how hackers really do ! \n",infoStyle);               
            }
        }catch(FileNotFoundException e){
            System.err.println(e);
        }catch (BadLocationException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }catch (IOException ex) {
            System.err.println(ex);
        } 
        
        
        
    }//GEN-LAST:event_m1FilebuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel entryPanel;
    private javax.swing.JButton entryPanelButton;
    private javax.swing.JScrollPane entryPanelScrollPanel;
    private javax.swing.JTextArea entryPanelText;
    private javax.swing.JLabel entryPanelTitle;
    private javax.swing.JLabel hackerLabel;
    private javax.swing.JTextPane hackerPane;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextPane infoPane;
    private javax.swing.JLayeredPane layoutPanel;
    private javax.swing.JButton m1Filebutton;
    private javax.swing.JButton m1HashButton;
    private javax.swing.JTextField m1HashField;
    private javax.swing.JButton m2AddWordButton;
    private javax.swing.JButton m2AutoButton;
    private javax.swing.JLabel m2ChoisirDic;
    private javax.swing.JComboBox m2ListDic;
    private javax.swing.JTextField m2TextField;
    private javax.swing.JButton m3AttakButton;
    private javax.swing.JButton m3ConfirmButton;
    private javax.swing.JButton m3FillDicoButton;
    private javax.swing.JTextField m3PassField;
    private javax.swing.JPanel mission1Panel;
    private javax.swing.JPanel mission2Panel;
    private javax.swing.JPanel mission3Panel;
    private javax.swing.JLayeredPane missionLayeredPanel;
    private javax.swing.JScrollPane scrollHackPane;
    private javax.swing.JScrollPane scrollInfoPane;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void setController(Controller c) {
        this.controller=c;
    }

    @Override
    public Controller getController() {
        return controller;
    }

    @Override
    public void setAppletDescriptionText(String s) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setMissionDescriptionText(String s) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
